parameters:
    wsseaccesstoken.factory.class: Onfan\WSSEAccessTokenBundle\Security\Factory\Factory

services:
    security.authentication.factory.wsseaccesstoken:
        class:  %wsseaccesstoken.factory.class%
        tags:
            - { name: security.listener.factory }