services:
    wsseaccesstoken.security.authentication.provider:
        class:  %wsseaccesstoken.authentication.provider.class%
        arguments: ['', %kernel.cache_dir%/security/nonces, 300]

    wsseaccesstoken.security.authentication.listener:
        class:  %wsseaccesstoken.authentication.listener.class%
        arguments: [@security.context, @security.authentication.manager]